name: flutter_branch_sdk
description: Flutter Plugin for Brach Metrics SDK - https:&#x2F;&#x2F;branch.io
version: 0.0.1
author: Rodrigo S. Marques <rodrigosmarques@gmail.com>
homepage: https://github.com/RodrigoSMarques/flutter_branch_sdk

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.rsmarques.flutter_branch_sdk
    pluginClass: FlutterBranchSdkPlugin

